### ISSUE TITLE
Encountered a problem in Special Judge

### ISSUE THREAD

**Issue by lumoeisu** [TengGit/LeetCodeCppLocalDev#1]
If I need to perform Special Judge, how should I use this library

**Comment by TengGit** [comment]
It depends on how the code in your OJ deal with the input/output. AFAIK there are 2 ways:

1. The code interacts with stdin/stdout directly. Codeforces and most OJs use this way.
2. The code is a function, which uses parameters to implement an algorithm. LeetCode uses this way.

In the former case, your Special Judge can process the output produced by submitted code, and judge the result.

In the latter case, either you can wrap the submitted code to interact with stdin/stdout, and judge the wrapped output using the above method; or you can directly call the submitted function and judge the result.
